name: hive_view_ce
description: "A new Flutter package project."
version: 0.0.1
homepage: flutter-dev.pl

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  hive_ce: ^2.8.0+2
  hive_ce_flutter: ^2.1.0
  shelf: ^1.4.0
  shelf_cors_headers: ^0.1.5
  shelf_flutter_asset: ^0.0.4
  shelf_router: ^1.0.0
  shelf_static: ^1.1.3
  shelf_web_socket: ^2.0.1
  shelf_packages_handler: ^3.0.2
  path_provider: ^2.1.5

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  hive_ce_generator: ^1.8.0
flutter:
  assets:
    - assets/
    - assets/web/
    - assets/web/assets/
    - assets/web/assets/fonts/
    - assets/web/assets/shaders/
    - assets/web/icons/
    - assets/web/canvaskit/
    - assets/web/canvaskit/chromium/
